In [ ]:
import pandas as pd
import io
import numpy as np
f = "https://raw.githubusercontent.com/AmujoeAdiday/MVPS/main/standardizedallstats_no_unname.csv"
file = pd.read_csv(f)
file

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W,L,W/L%,GB,PS/G,PA/G,SRS,TS%,Rank,MVP
0,?an Tabak,C,-0.886218,HOU,-0.716531,-0.912480,-1.501674,-1.133253,-1.180332,0.132625,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,0.021818,0,0
1,Adrian Caldwell,PF,0.174886,HOU,-1.903423,-0.912480,-1.558538,-1.353423,-1.351556,-1.999926,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,-1.687118,0,0
2,Carl Herrera,PF,0.174886,HOU,0.232983,-0.044511,0.100016,-0.164503,-0.324215,0.867987,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,0.293066,0,0
3,Charles Jones,PF,2.562368,HOU,-2.061675,-0.912480,-0.828774,-1.265355,-1.265944,-1.127996,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,-1.371853,0,0
4,Chucky Brown,SF,-0.355666,HOU,-0.558279,-0.445112,-0.080055,-0.252571,-0.581050,1.708401,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,1.134430,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Mike Dunleavy,SG-PF,-0.091724,IND,1.113670,0.769627,1.025399,0.736740,0.780007,0.158034,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.302459,0,0
14088,Orien Greene,SG,-0.555920,IND,-0.563355,-0.933388,-1.363893,-1.075008,-1.096115,-0.660559,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.908281,0,0
14089,Rawle Marshall,SG,-0.555920,IND,-0.604258,-0.863877,-1.099466,-0.986630,-0.948555,-0.771726,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.480678,0,0
14090,Shawne Williams,SG,-1.484312,IND,-0.358839,-0.829121,-0.806706,-0.633118,-0.674514,0.329838,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.202020,0,0
14091,Troy Murphy,PF,-0.091724,IND,0.541028,0.734872,0.619314,0.383229,0.379486,0.218671,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.370827,0,0

In [ ]:
years_trained = [year for year in range(2007,2022)]
file = file[file.Year.isin(years_trained)]

In [ ]:
file["Is_MVP_or_MVP_candidate"] = file["MVP"].apply(lambda x : 0 if x == 0 else 1)
file

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,L,W/L%,GB,PS/G,PA/G,SRS,TS%,Rank,MVP,Is_MVP_or_MVP_candidate
6829,A.J. Hammons,C,-0.554215,DAL,-1.279530,-0.881347,-1.379770,-1.074999,-1.108197,-0.350256,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,-0.527129,0,0,0
6830,Ben Bentil,PF,-1.244852,DAL,-2.044464,-0.881347,-1.832327,-1.445663,-1.307116,-4.360780,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,-5.835876,0,0,0
6831,DeAndre Liggins,SG,0.366635,DAL,0.330859,-0.219692,-0.816833,-1.028667,-1.019789,-0.528502,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,-0.433768,0,0,0
6832,Devin Harris,PG,1.517696,DAL,0.451638,-0.881347,-0.353238,-0.472672,-0.378828,-0.409671,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,0.269501,0,0,0
6833,Dirk Nowitzki,PF,2.668758,DAL,0.008781,0.999146,0.717446,1.102647,1.256727,-0.033375,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,-0.018536,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Mike Dunleavy,SG-PF,-0.091724,IND,1.113670,0.769627,1.025399,0.736740,0.780007,0.158034,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.302459,0,0,0
14088,Orien Greene,SG,-0.555920,IND,-0.563355,-0.933388,-1.363893,-1.075008,-1.096115,-0.660559,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.908281,0,0,0
14089,Rawle Marshall,SG,-0.555920,IND,-0.604258,-0.863877,-1.099466,-0.986630,-0.948555,-0.771726,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.480678,0,0,0
14090,Shawne Williams,SG,-1.484312,IND,-0.358839,-0.829121,-0.806706,-0.633118,-0.674514,0.329838,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.202020,0,0,0
14091,Troy Murphy,PF,-0.091724,IND,0.541028,0.734872,0.619314,0.383229,0.379486,0.218671,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.370827,0,0,0

In [ ]:
file.iloc[np.where(file.MVP == 0)]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,L,W/L%,GB,PS/G,PA/G,SRS,TS%,Rank,MVP,Is_MVP_or_MVP_candidate
6829,A.J. Hammons,C,-0.554215,DAL,-1.279530,-0.881347,-1.379770,-1.074999,-1.108197,-0.350256,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,-0.527129,0,0,0
6830,Ben Bentil,PF,-1.244852,DAL,-2.044464,-0.881347,-1.832327,-1.445663,-1.307116,-4.360780,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,-5.835876,0,0,0
6831,DeAndre Liggins,SG,0.366635,DAL,0.330859,-0.219692,-0.816833,-1.028667,-1.019789,-0.528502,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,-0.433768,0,0,0
6832,Devin Harris,PG,1.517696,DAL,0.451638,-0.881347,-0.353238,-0.472672,-0.378828,-0.409671,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,0.269501,0,0,0
6833,Dirk Nowitzki,PF,2.668758,DAL,0.008781,0.999146,0.717446,1.102647,1.256727,-0.033375,...,0.703571,-0.706557,1.064889,-1.872876,-1.230109,-0.587617,-0.018536,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Mike Dunleavy,SG-PF,-0.091724,IND,1.113670,0.769627,1.025399,0.736740,0.780007,0.158034,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.302459,0,0,0
14088,Orien Greene,SG,-0.555920,IND,-0.563355,-0.933388,-1.363893,-1.075008,-1.096115,-0.660559,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.908281,0,0,0
14089,Rawle Marshall,SG,-0.555920,IND,-0.604258,-0.863877,-1.099466,-0.986630,-0.948555,-0.771726,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.480678,0,0,0
14090,Shawne Williams,SG,-1.484312,IND,-0.358839,-0.829121,-0.806706,-0.633118,-0.674514,0.329838,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.202020,0,0,0
14091,Troy Murphy,PF,-0.091724,IND,0.541028,0.734872,0.619314,0.383229,0.379486,0.218671,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.370827,0,0,0

In [ ]:
file.iloc[np.where(file.MVP == 1)]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,L,W/L%,GB,PS/G,PA/G,SRS,TS%,Rank,MVP,Is_MVP_or_MVP_candidate
7080,Russell Westbrook,PG,0.366635,OKC,1.095793,1.939393,1.622560,3.280293,3.776365,-0.152206,...,-0.561853,0.560798,-0.834036,0.257405,0.040254,0.299013,0.290828,1,1,1
7514,LeBron James,SF,-0.395207,CLE,0.823077,1.585809,1.769083,3.188023,2.880092,0.612767,...,-1.563728,1.563476,-1.184726,0.431050,-1.085423,1.425610,1.063340,1,1,1
8151,Derrick Rose,PG,-1.124383,CHI,1.058950,1.808557,1.710970,2.702243,2.896198,0.035611,...,-1.615919,1.615407,-1.323048,-0.222270,-1.721791,1.456816,0.410703,1,1,1
8619,LeBron James,SF,0.083834,MIA,0.937566,1.770770,1.863063,3.436256,2.815309,1.141935,...,-1.295738,1.295828,-1.215931,0.586635,-0.997762,1.239116,1.177427,1,1,1
9087,LeBron James,PF,0.319157,MIA,0.861372,1.658344,1.832723,3.467406,2.554944,1.350202,...,-1.992608,1.996790,-1.196755,1.203316,-0.886715,1.589218,1.449428,1,1,1
9430,Kevin Durant,SF,-0.362528,OKC,1.093772,1.866592,1.890670,3.485308,3.108723,0.666716,...,-1.418221,1.420416,-1.253092,1.255490,-0.303818,1.410109,1.288840,1,1,1
9908,Stephen Curry,PG,-0.127957,GSW,1.117032,1.986724,1.377167,2.556150,2.290410,0.550051,...,-1.971356,1.970091,-1.139302,2.394710,-0.055085,2.130393,1.328541,1,1,1
10435,Kobe Bryant,SG,0.529921,LAL,1.067649,1.802519,1.742344,2.894317,2.967092,0.202032,...,-1.163888,1.162475,-1.164955,1.720837,0.280806,1.390792,0.758637,1,1,1
10747,LeBron James,SF,-0.603226,CLE,1.040021,1.807599,1.576974,2.919214,2.743993,0.479251,...,-1.792981,1.792625,-1.247456,0.093998,-1.617291,1.909513,0.877656,1,1,1
11245,Stephen Curry,PG,0.092520,GSW,0.997516,1.807327,1.523041,3.450690,2.996771,0.692706,...,-2.367828,2.366801,-1.165466,3.337264,0.392381,2.173636,1.858802,1,1,1
11557,James Harden,SG,0.457613,HOU,0.861438,1.756098,1.725793,2.778437,2.942860,0.069406,...,-1.988615,1.990348,-0.990434,1.640028,-0.737450,1.958396,0.706327,1,1,1
12433,Giannis Antetokounmpo,PF,-0.452508,MIL,0.873471,1.743329,1.474625,3.081202,2.234849,1.234925,...,-1.596639,1.598697,-1.040833,1.681146,-0.514978,1.727675,1.038002,1,1,1
13026,Giannis Antetokounmpo,PF,-0.136288,MIL,0.913219,1.773254,1.182053,3.386587,2.659088,0.985582,...,-1.947924,1.802724,-1.165661,1.865731,-0.885869,2.043349,0.747554,1,1,1
13105,Nikola Joki?,C,-0.135227,DEN,1.415361,2.243683,1.587745,2.947277,2.243551,1.096774,...,-1.120016,1.121655,-0.633307,0.736271,-0.622090,1.034131,0.983476,1,1,1
13949,Dirk Nowitzki,PF,0.372472,DAL,0.950058,1.777534,1.469260,2.460111,2.213448,0.663339,...,-2.477076,2.476057,-1.203346,0.346347,-1.334827,2.000638,0.989980,1,1,1

In [ ]:
file = file.drop(["MVP"], axis =1 )

In [ ]:
overal_col_name = file.columns.values
overal_col_name

array(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Year', 'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%',
       'GB', 'PS/G', 'PA/G', 'SRS', 'TS%', 'Rank',
       'Is_MVP_or_MVP_candidate'], dtype=object)

In [ ]:
def get_dictionary(col_name):
  return dict(zip(file.index, file[col_name]))
Player = get_dictionary("Player")
Team = get_dictionary("Tm")
Year = get_dictionary("Year")

In [ ]:
df = file.drop(["Player","GS","FG","FGA","FG%","eFG%","3P%","2P","2P%","FT","FT%","ORB","DRB","Year","Pts Won","Pts Max","Share","W","L","GB","Rank","PS/G","PA/G","Tm","Pos","Team"], axis = 1)
df["Is_MVP_or_MVP_candidate"] = df["Is_MVP_or_MVP_candidate"].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7263 entries, 6829 to 14091
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      7263 non-null   float64
 1   G                        7263 non-null   float64
 2   MP                       7263 non-null   float64
 3   3P                       7263 non-null   float64
 4   3PA                      7263 non-null   float64
 5   2PA                      7263 non-null   float64
 6   FTA                      7263 non-null   float64
 7   TRB                      7263 non-null   float64
 8   AST                      7263 non-null   float64
 9   STL                      7263 non-null   float64
 10  BLK                      7263 non-null   float64
 11  TOV                      7263 non-null   float64
 12  PF                       7263 non-null   float64
 13  PTS                      7263 non-null   float64
 14  W/L%                     7263 non-null   float64
 15  SRS                      7263 non-null   float64
 16  TS%                      7263 non-null   float64
 17  Is_MVP_or_MVP_candidate  7263 non-null   object
dtypes: float64(17), object(1)
memory usage: 1.1+ MB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7263 entries, 6829 to 14091
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      7263 non-null   float64
 1   G                        7263 non-null   float64
 2   MP                       7263 non-null   float64
 3   3P                       7263 non-null   float64
 4   3PA                      7263 non-null   float64
 5   2PA                      7263 non-null   float64
 6   FTA                      7263 non-null   float64
 7   TRB                      7263 non-null   float64
 8   AST                      7263 non-null   float64
 9   STL                      7263 non-null   float64
 10  BLK                      7263 non-null   float64
 11  TOV                      7263 non-null   float64
 12  PF                       7263 non-null   float64
 13  PTS                      7263 non-null   float64
 14  W/L%                     7263 non-null   float64
 15  SRS                      7263 non-null   float64
 16  TS%                      7263 non-null   float64
 17  Is_MVP_or_MVP_candidate  7263 non-null   object
dtypes: float64(17), object(1)
memory usage: 1.1+ MB

In [ ]:
features = df.columns.values[:-1]

In [ ]:
!pip install RuleFit

Collecting RuleFit
  Downloading rulefit-0.3.1.tar.gz (25 kB)
Requirement already satisfied: numpy>=1.16.1 in /usr/local/lib/python3.7/dist-packages (from RuleFit) (1.21.6)
Requirement already satisfied: pandas>=0.24.1 in /usr/local/lib/python3.7/dist-packages (from RuleFit) (1.3.5)
Requirement already satisfied: scikit-learn>=0.20.2 in /usr/local/lib/python3.7/dist-packages (from RuleFit) (1.0.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.1->RuleFit) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.1->RuleFit) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.1->RuleFit) (1.15.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.2->RuleFit) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.2->RuleFit) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.2->RuleFit) (3.1.0)
Building wheels for collected packages: RuleFit
  Building wheel for RuleFit (setup.py) ... done
  Created wheel for RuleFit: filename=rulefit-0.3.1-py3-none-any.whl size=7826 sha256=143a4229965727009f2af8591d74f7c5e02feba4d5ecf9a98849f3d4a671dbb8
  Stored in directory: /root/.cache/pip/wheels/93/1f/59/0e2baa7508212197e234ac1dc1e6ddf05f0f9b7179378b6e6f
Successfully built RuleFit
Installing collected packages: RuleFit
Successfully installed RuleFit-0.3.1

In [ ]:
from sklearn.model_selection import train_test_split
from rulefit import RuleFit

X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
rf = RuleFit(max_rules=1,rfmode= "classify", model_type="r")
rf.fit(X_train, y_train,features )

RuleFit(max_rules=1, model_type='r', rfmode='classify',
        tree_generator=GradientBoostingClassifier(learning_rate=0.01,
                                                  max_depth=100,
                                                  max_leaf_nodes=2,
                                                  n_estimators=1,
                                                  random_state=0,
                                                  subsample=0.09592773425194975))

In [ ]:
rules = rf.get_rules()
rules

                        rule  type      coef   support  importance
0  FTA <= 2.8089007139205933  rule -4.132595  0.969479    0.710868
1   FTA > 2.8089007139205933  rule  0.097159  0.030521    0.016713

In [ ]:
rules= rules.sort_values(by="importance", ascending=False)
pd.set_option("display.max_colwidth", 999)
rules.head(10)

                        rule  type      coef   support  importance
0  FTA <= 2.8089007139205933  rule -4.132595  0.969479    0.710868
1   FTA > 2.8089007139205933  rule  0.097159  0.030521    0.016713

In [ ]:
class_0 = df.iloc[np.where(df.Is_MVP_or_MVP_candidate == "0")]
class_0

,Age,G,MP,3P,3PA,2PA,FTA,TRB,AST,STL,BLK,TOV,PF,PTS,W/L%,SRS,TS%,Is_MVP_or_MVP_candidate
6829,-0.554215,-1.279530,-1.379770,-0.751925,-0.867548,-0.936267,-0.555623,-0.809237,-0.923072,-1.522622,0.496858,-0.765335,-0.922376,-1.027864,-0.706557,-0.587617,-0.527129,0
6830,-1.244852,-2.044464,-1.832327,-1.016637,-0.970548,-1.168290,-1.076141,-1.179838,-1.036315,-1.522622,-0.940482,-1.021237,-1.871536,-1.391023,-0.706557,-0.587617,-5.835876,0
6831,0.366635,0.330859,-0.816833,-0.619568,-0.764549,-0.936267,-0.729129,-0.768060,-0.526721,0.425372,-0.461368,-0.509434,-0.515593,-0.978342,-0.706557,-0.587617,-0.433768,0
6832,1.517696,0.451638,-0.353238,0.174569,0.265446,-0.646239,0.080565,-0.644526,0.152739,0.181873,-0.700925,-0.253532,-0.108810,-0.285039,-0.706557,-0.587617,0.269501,0
6833,2.668758,0.008781,0.717446,0.968705,0.883443,1.151939,0.138400,1.208476,-0.186991,-0.061626,0.736415,-0.253532,0.569161,0.953004,-0.706557,-0.587617,-0.018536,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,-0.091724,1.113670,1.025399,0.617089,0.763783,0.587060,0.557555,0.723273,0.570653,0.877153,-0.182383,0.660981,0.628128,0.730006,-0.537997,-0.676847,0.302459,0
14088,-0.555920,-0.563355,-1.363893,-0.774400,-0.660391,-1.038473,-0.818088,-0.967234,-0.698884,-0.495522,-0.585917,-0.663611,-1.272335,-1.066681,-0.537997,-0.676847,-0.908281,0
14089,-0.555920,-0.604258,-1.099466,-0.619790,-0.541710,-0.886079,-0.563339,-1.128235,-0.809279,-0.724301,-0.585917,-0.904446,-1.628672,-0.907682,-0.537997,-0.676847,-0.480678,0
14090,-1.484312,-0.358839,-0.806706,-0.155960,-0.185666,-0.759085,-0.919988,-0.685483,-0.698884,-1.181859,-0.384150,-0.904446,-0.559662,-0.685084,-0.537997,-0.676847,0.202020,0
14091,-0.091724,0.541028,0.619314,0.617089,0.467080,0.282272,-0.053842,1.045274,0.073878,0.190816,0.422918,-0.181941,1.103244,0.332509,-0.537997,-0.676847,0.370827,0

In [ ]:
class_1 = df.iloc[np.where(df.Is_MVP_or_MVP_candidate == "1")]
class_1

,Age,G,MP,3P,3PA,2PA,FTA,TRB,AST,STL,BLK,TOV,PF,PTS,W/L%,SRS,TS%,Is_MVP_or_MVP_candidate
6919,0.136422,0.894494,1.534256,3.218760,3.252431,1.790002,3.839859,-0.356281,2.304360,0.668871,-0.461368,2.177533,0.704756,3.379568,1.101833,0.567176,1.083640,1
7007,-0.784427,0.854235,1.788130,-0.354856,-0.198051,4.023223,3.897694,3.390901,0.152739,1.642869,4.329765,1.665729,0.704756,3.231003,-0.610208,-0.384683,0.605381,1
7048,0.366635,0.330859,1.490104,1.498130,1.449940,1.964019,2.509647,1.949677,1.681522,1.155870,2.892425,1.409828,0.297973,2.752293,2.369188,2.765632,1.396498,1
7054,0.366635,1.015273,1.490104,4.409966,4.024928,1.035928,1.584282,0.384919,2.700711,2.860365,-0.461368,2.433434,0.840350,2.785308,2.369188,2.765632,1.061002,1
7080,0.366635,1.095793,1.622560,2.292267,2.582935,3.501171,4.938730,2.937944,4.852332,2.373366,0.017745,5.504253,0.840350,3.825263,0.560798,0.299013,0.290828,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13949,0.372472,0.950058,1.469260,0.617089,0.467080,2.466582,2.493645,2.172279,0.901836,0.190816,0.826451,1.022234,0.271791,2.606192,2.476057,2.000638,0.989980,1
13972,0.836668,1.031864,1.270939,-0.774400,-0.779072,2.212592,2.493645,2.856531,0.901836,0.419595,4.054722,1.865156,0.628128,1.874797,1.625939,2.290023,0.730476,1
13973,-0.555920,0.909155,1.119838,-0.465180,-0.541710,2.136395,1.168951,-0.121981,2.060979,1.105932,-0.585917,1.503904,-0.203325,1.652199,1.625939,2.290023,0.669302,1
14015,0.140374,0.663737,1.431485,2.008578,2.365979,2.593576,2.391745,0.723273,2.612951,1.563491,0.221151,2.105991,-0.084546,2.606192,1.061770,1.394824,0.049740,1
14022,0.836668,0.868252,1.771463,-0.465180,-0.423028,2.949162,2.238896,3.742035,1.288217,1.334712,2.642354,1.744739,0.509349,2.256395,-0.823946,-0.822892,0.368273,1