In [ ]:
import pandas as pd
import io
import numpy as np
f = "https://raw.githubusercontent.com/AmujoeAdiday/MVPS/main/standardizedallstats_no_unname.csv"
file = pd.read_csv(f)
file

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W,L,W/L%,GB,PS/G,PA/G,SRS,TS%,Rank,MVP
0,?an Tabak,C,-0.886218,HOU,-0.716531,-0.912480,-1.501674,-1.133253,-1.180332,0.132625,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,0.021818,0,0
1,Adrian Caldwell,PF,0.174886,HOU,-1.903423,-0.912480,-1.558538,-1.353423,-1.351556,-1.999926,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,-1.687118,0,0
2,Carl Herrera,PF,0.174886,HOU,0.232983,-0.044511,0.100016,-0.164503,-0.324215,0.867987,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,0.293066,0,0
3,Charles Jones,PF,2.562368,HOU,-2.061675,-0.912480,-0.828774,-1.265355,-1.265944,-1.127996,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,-1.371853,0,0
4,Chucky Brown,SF,-0.355666,HOU,-0.558279,-0.445112,-0.080055,-0.252571,-0.581050,1.708401,...,0.473361,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,1.134430,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Mike Dunleavy,SG-PF,-0.091724,IND,1.113670,0.769627,1.025399,0.736740,0.780007,0.158034,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.302459,0,0
14088,Orien Greene,SG,-0.555920,IND,-0.563355,-0.933388,-1.363893,-1.075008,-1.096115,-0.660559,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.908281,0,0
14089,Rawle Marshall,SG,-0.555920,IND,-0.604258,-0.863877,-1.099466,-0.986630,-0.948555,-0.771726,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.480678,0,0
14090,Shawne Williams,SG,-1.484312,IND,-0.358839,-0.829121,-0.806706,-0.633118,-0.674514,0.329838,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.202020,0,0
14091,Troy Murphy,PF,-0.091724,IND,0.541028,0.734872,0.619314,0.383229,0.379486,0.218671,...,-0.539712,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.370827,0,0

In [ ]:
file["Is_MVP_or_MVP_candidate"] = file["MVP"].apply(lambda x : 0 if x == 0 else 1)
file

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,L,W/L%,GB,PS/G,PA/G,SRS,TS%,Rank,MVP,Is_MVP_or_MVP_candidate
0,?an Tabak,C,-0.886218,HOU,-0.716531,-0.912480,-1.501674,-1.133253,-1.180332,0.132625,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,0.021818,0,0,0
1,Adrian Caldwell,PF,0.174886,HOU,-1.903423,-0.912480,-1.558538,-1.353423,-1.351556,-1.999926,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,-1.687118,0,0,0
2,Carl Herrera,PF,0.174886,HOU,0.232983,-0.044511,0.100016,-0.164503,-0.324215,0.867987,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,0.293066,0,0,0
3,Charles Jones,PF,2.562368,HOU,-2.061675,-0.912480,-0.828774,-1.265355,-1.265944,-1.127996,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,-1.371853,0,0,0
4,Chucky Brown,SF,-0.355666,HOU,-0.558279,-0.445112,-0.080055,-0.252571,-0.581050,1.708401,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,1.134430,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Mike Dunleavy,SG-PF,-0.091724,IND,1.113670,0.769627,1.025399,0.736740,0.780007,0.158034,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.302459,0,0,0
14088,Orien Greene,SG,-0.555920,IND,-0.563355,-0.933388,-1.363893,-1.075008,-1.096115,-0.660559,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.908281,0,0,0
14089,Rawle Marshall,SG,-0.555920,IND,-0.604258,-0.863877,-1.099466,-0.986630,-0.948555,-0.771726,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.480678,0,0,0
14090,Shawne Williams,SG,-1.484312,IND,-0.358839,-0.829121,-0.806706,-0.633118,-0.674514,0.329838,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.202020,0,0,0
14091,Troy Murphy,PF,-0.091724,IND,0.541028,0.734872,0.619314,0.383229,0.379486,0.218671,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.370827,0,0,0

In [ ]:
file.iloc[np.where(file.MVP == 0)]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,L,W/L%,GB,PS/G,PA/G,SRS,TS%,Rank,MVP,Is_MVP_or_MVP_candidate
0,?an Tabak,C,-0.886218,HOU,-0.716531,-0.912480,-1.501674,-1.133253,-1.180332,0.132625,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,0.021818,0,0,0
1,Adrian Caldwell,PF,0.174886,HOU,-1.903423,-0.912480,-1.558538,-1.353423,-1.351556,-1.999926,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,-1.687118,0,0,0
2,Carl Herrera,PF,0.174886,HOU,0.232983,-0.044511,0.100016,-0.164503,-0.324215,0.867987,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,0.293066,0,0,0
3,Charles Jones,PF,2.562368,HOU,-2.061675,-0.912480,-0.828774,-1.265355,-1.265944,-1.127996,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,-1.371853,0,0,0
4,Chucky Brown,SF,-0.355666,HOU,-0.558279,-0.445112,-0.080055,-0.252571,-0.581050,1.708401,...,-0.473361,0.472185,-0.112700,0.431817,-0.006957,0.509455,1.134430,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Mike Dunleavy,SG-PF,-0.091724,IND,1.113670,0.769627,1.025399,0.736740,0.780007,0.158034,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.302459,0,0,0
14088,Orien Greene,SG,-0.555920,IND,-0.563355,-0.933388,-1.363893,-1.075008,-1.096115,-0.660559,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.908281,0,0,0
14089,Rawle Marshall,SG,-0.555920,IND,-0.604258,-0.863877,-1.099466,-0.986630,-0.948555,-0.771726,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,-0.480678,0,0,0
14090,Shawne Williams,SG,-1.484312,IND,-0.358839,-0.829121,-0.806706,-0.633118,-0.674514,0.329838,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.202020,0,0,0
14091,Troy Murphy,PF,-0.091724,IND,0.541028,0.734872,0.619314,0.383229,0.379486,0.218671,...,0.539712,-0.537997,0.472111,-0.766293,-0.165552,-0.676847,0.370827,0,0,0

In [ ]:
file.iloc[np.where(file.MVP == 1)]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,L,W/L%,GB,PS/G,PA/G,SRS,TS%,Rank,MVP,Is_MVP_or_MVP_candidate
261,David Robinson,C,0.440161,SAS,1.024244,1.791576,1.635364,2.873849,2.458167,0.941523,...,-1.620874,1.619819,-1.231418,1.056553,-0.181700,1.271414,0.847406,1,1,1
750,Michael Jordan,SG,1.218420,CHI,1.036212,1.776100,1.562983,3.636170,3.423448,0.630933,...,-2.271336,2.271545,-1.689167,1.379951,-1.513761,2.387691,0.878272,1,1,1
923,Karl Malone,PF,1.293791,UTA,1.087256,1.804233,1.448794,3.359364,2.667219,1.326763,...,-1.521630,1.519003,-1.427789,1.575475,-0.526445,1.558084,1.064149,1,1,1
1618,Michael Jordan,SG,1.479508,CHI,1.060670,1.823373,1.692793,3.528127,3.534573,0.391081,...,-1.409637,1.409173,-1.245899,0.334189,-1.320924,1.400490,0.372511,1,1,1
1738,Shaquille O'Neal,C,-0.149541,LAL,0.917903,1.641375,1.911396,4.164893,3.071593,1.615495,...,-2.028642,2.027141,-1.220542,0.870811,-1.288111,1.878155,0.936875,1,1,1
2200,Allen Iverson,SG,-0.582355,PHI,0.647681,1.487230,2.016154,3.469925,3.886654,-0.028043,...,-1.198908,1.199549,-1.186638,-0.001876,-1.191156,0.861131,0.296723,1,1,1
3024,Kevin Garnett,PF,-0.001019,MIN,1.086317,1.833031,1.779771,3.226515,2.708473,0.908834,...,-1.564324,1.561476,-1.355612,0.320932,-0.879909,1.495037,0.687675,1,1,1
3225,Steve Nash,PG,0.720706,PHO,0.840179,1.642752,1.322499,1.245352,0.984494,0.798906,...,-1.689023,1.687919,-1.083988,3.132155,1.524523,1.785919,1.153165,1,1,1
3729,Steve Nash,PG,1.066335,PHO,1.004843,1.757152,1.389307,1.696814,1.411445,0.729678,...,-1.169266,1.172086,-1.360407,2.844398,1.342198,1.486270,1.426187,1,1,1
4157,Tim Duncan,PF,-0.473865,SAS,1.096631,1.821891,1.877675,2.841233,2.372729,1.029442,...,-1.560134,1.556952,-1.269039,0.317074,-1.480290,1.595233,1.088908,1,1,1
4796,Tim Duncan,PF,-0.239260,SAS,0.979611,1.728051,1.766462,2.627074,2.154322,1.065894,...,-1.660797,1.661429,-1.162806,0.175420,-1.256316,1.390582,0.844267,1,1,1
5051,Michael Jordan,SG,0.047505,CHI,0.939231,1.693905,1.510330,3.460703,2.986594,1.050243,...,-1.629795,1.629997,-1.496842,0.643321,-0.860592,1.828144,1.173713,1,1,1
5452,Michael Jordan,SG,0.315788,CHI,0.878374,1.606157,1.669325,3.442243,3.118308,0.817533,...,-2.043799,2.043840,-1.302938,0.912588,-1.361063,2.183485,1.025388,1,1,1
5920,Charles Barkley,PF,0.551044,PHO,0.734569,1.548673,1.612873,2.550550,2.268234,0.853168,...,-1.666003,1.664604,-1.416701,2.403820,0.295771,1.328171,1.242505,1,1,1
6362,Hakeem Olajuwon,C,1.083953,HOU,0.922141,1.707732,1.960240,3.546677,3.083863,0.879045,...,-1.207115,1.205912,-1.261441,-0.097297,-1.044734,0.849100,0.667959,1,1,1
6445,Karl Malone,PF,1.654425,UTA,0.919922,1.705809,1.623246,2.580668,2.231918,0.668731,...,-1.544812,1.544812,-1.176778,0.466533,-1.024425,1.303148,0.824386,1,1,1
7080,Russell Westbrook,PG,0.366635,OKC,1.095793,1.939393,1.622560,3.280293,3.776365,-0.152206,...,-0.561853,0.560798,-0.834036,0.257405,0.040254,0.299013,0.290828,1,1,1
7514,LeBron James,SF,-0.395207,CLE,0.823077,1.585809,1.769083,3.188023,2.880092,0.612767,...,-1.563728,1.563476,-1.184726,0.431050,-1.085423,1.425610,1.063340,1,1,1
8151,Derrick Rose,PG,-1.124383,CHI,1.058950,1.808557,1.710970,2.702243,2.896198,0.035611,...,-1.615919,1.615407,-1.323048,-0.222270,-1.721791,1.456816,0.410703,1,1,1
8619,LeBron James,SF,0.083834,MIA,0.937566,1.770770,1.863063,3.436256,2.815309,1.141935,...,-1.295738,1.295828,-1.215931,0.586635,-0.997762,1.239116,1.177427,1,1,1
9087,LeBron James,PF,0.319157,MIA,0.861372,1.658344,1.832723,3.467406,2.554944,1.350202,...,-1.992608,1.996790,-1.196755,1.203316,-0.886715,1.589218,1.449428,1,1,1
9430,Kevin Durant,SF,-0.362528,OKC,1.093772,1.866592,1.890670,3.485308,3.108723,0.666716,...,-1.418221,1.420416,-1.253092,1.255490,-0.303818,1.410109,1.288840,1,1,1
9908,Stephen Curry,PG,-0.127957,GSW,1.117032,1.986724,1.377167,2.556150,2.290410,0.550051,...,-1.971356,1.970091,-1.139302,2.394710,-0.055085,2.130393,1.328541,1,1,1
10435,Kobe Bryant,SG,0.529921,LAL,1.067649,1.802519,1.742344,2.894317,2.967092,0.202032,...,-1.163888,1.162475,-1.164955,1.720837,0.280806,1.390792,0.758637,1,1,1
10747,LeBron James,SF,-0.603226,CLE,1.040021,1.807599,1.576974,2.919214,2.743993,0.479251,...,-1.792981,1.792625,-1.247456,0.093998,-1.617291,1.909513,0.877656,1,1,1
11245,Stephen Curry,PG,0.092520,GSW,0.997516,1.807327,1.523041,3.450690,2.996771,0.692706,...,-2.367828,2.366801,-1.165466,3.337264,0.392381,2.173636,1.858802,1,1,1
11557,James Harden,SG,0.457613,HOU,0.861438,1.756098,1.725793,2.778437,2.942860,0.069406,...,-1.988615,1.990348,-0.990434,1.640028,-0.737450,1.958396,0.706327,1,1,1
12433,Giannis Antetokounmpo,PF,-0.452508,MIL,0.873471,1.743329,1.474625,3.081202,2.234849,1.234925,...,-1.596639,1.598697,-1.040833,1.681146,-0.514978,1.727675,1.038002,1,1,1
13026,Giannis Antetokounmpo,PF,-0.136288,MIL,0.913219,1.773254,1.182053,3.386587,2.659088,0.985582,...,-1.947924,1.802724,-1.165661,1.865731,-0.885869,2.043349,0.747554,1,1,1
13105,Nikola Joki?,C,-0.135227,DEN,1.415361,2.243683,1.587745,2.947277,2.243551,1.096774,...,-1.120016,1.121655,-0.633307,0.736271,-0.622090,1.034131,0.983476,1,1,1
13949,Dirk Nowitzki,PF,0.372472,DAL,0.950058,1.777534,1.469260,2.460111,2.213448,0.663339,...,-2.477076,2.476057,-1.203346,0.346347,-1.334827,2.000638,0.989980,1,1,1

In [ ]:
file = file.drop(["MVP"], axis =1 )

In [ ]:
overal_col_name = file.columns.values
overal_col_name

array(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Year', 'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%',
       'GB', 'PS/G', 'PA/G', 'SRS', 'TS%', 'Rank',
       'Is_MVP_or_MVP_candidate'], dtype=object)

In [ ]:
def get_dictionary(col_name):
  return dict(zip(file.index, file[col_name]))
Player = get_dictionary("Player")
Team = get_dictionary("Tm")
Year = get_dictionary("Year")

In [ ]:
df = file.drop(["Player","GS","FG","FGA","FG%","eFG%","3P%","2P","2P%","FT","FT%","ORB","DRB","Year","Pts Won","Pts Max","Share","W","L","GB","Rank","PS/G","PA/G","Tm","Pos","Team"], axis = 1)
df["Is_MVP_or_MVP_candidate"] = df["Is_MVP_or_MVP_candidate"].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14092 entries, 0 to 14091
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      14092 non-null  float64
 1   G                        14092 non-null  float64
 2   MP                       14092 non-null  float64
 3   3P                       14092 non-null  float64
 4   3PA                      14092 non-null  float64
 5   2PA                      14092 non-null  float64
 6   FTA                      14092 non-null  float64
 7   TRB                      14092 non-null  float64
 8   AST                      14092 non-null  float64
 9   STL                      14092 non-null  float64
 10  BLK                      14092 non-null  float64
 11  TOV                      14092 non-null  float64
 12  PF                       14092 non-null  float64
 13  PTS                      14092 non-null  float64
 14  W/L%                     14092 non-null  float64
 15  SRS                      14092 non-null  float64
 16  TS%                      14092 non-null  float64
 17  Is_MVP_or_MVP_candidate  14092 non-null  object
dtypes: float64(17), object(1)
memory usage: 1.9+ MB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14092 entries, 0 to 14091
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      14092 non-null  float64
 1   G                        14092 non-null  float64
 2   MP                       14092 non-null  float64
 3   3P                       14092 non-null  float64
 4   3PA                      14092 non-null  float64
 5   2PA                      14092 non-null  float64
 6   FTA                      14092 non-null  float64
 7   TRB                      14092 non-null  float64
 8   AST                      14092 non-null  float64
 9   STL                      14092 non-null  float64
 10  BLK                      14092 non-null  float64
 11  TOV                      14092 non-null  float64
 12  PF                       14092 non-null  float64
 13  PTS                      14092 non-null  float64
 14  W/L%                     14092 non-null  float64
 15  SRS                      14092 non-null  float64
 16  TS%                      14092 non-null  float64
 17  Is_MVP_or_MVP_candidate  14092 non-null  object
dtypes: float64(17), object(1)
memory usage: 1.9+ MB

In [ ]:
features = df.columns.values[:-1]

In [ ]:
!pip install RuleFit

Requirement already satisfied: RuleFit in /usr/local/lib/python3.7/dist-packages (0.3.1)
Requirement already satisfied: scikit-learn>=0.20.2 in /usr/local/lib/python3.7/dist-packages (from RuleFit) (1.0.2)
Requirement already satisfied: numpy>=1.16.1 in /usr/local/lib/python3.7/dist-packages (from RuleFit) (1.21.6)
Requirement already satisfied: pandas>=0.24.1 in /usr/local/lib/python3.7/dist-packages (from RuleFit) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.1->RuleFit) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.1->RuleFit) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.1->RuleFit) (1.15.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.2->RuleFit) (1.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.2->RuleFit) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.2->RuleFit) (1.1.0)

In [ ]:
from sklearn.model_selection import train_test_split
from rulefit import RuleFit

X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
rf = RuleFit(max_rules=1,rfmode= "classify", model_type="r")
rf.fit(X_train, y_train,features )

RuleFit(max_rules=1, model_type='r', rfmode='classify',
        tree_generator=GradientBoostingClassifier(learning_rate=0.01,
                                                  max_depth=100,
                                                  max_leaf_nodes=2,
                                                  n_estimators=1,
                                                  random_state=0,
                                                  subsample=0.065381558515809))

In [ ]:
rules = rf.get_rules()
rules

                       rule  type  coef   support  importance
0   PTS > 1.667323112487793  rule   0.0  0.081411         0.0
1  PTS <= 1.667323112487793  rule   0.0  0.918589         0.0

In [ ]:
rules= rules.sort_values(by="importance", ascending=False)
pd.set_option("display.max_colwidth", 999)
rules.head(10)

                       rule  type  coef   support  importance
0   PTS > 1.667323112487793  rule   0.0  0.081411         0.0
1  PTS <= 1.667323112487793  rule   0.0  0.918589         0.0

In [ ]:
class_0 = df.iloc[np.where(df.Is_MVP_or_MVP_candidate == "0")]
class_0

,Age,G,MP,3P,3PA,2PA,FTA,TRB,AST,STL,BLK,TOV,PF,PTS,W/L%,SRS,TS%,Is_MVP_or_MVP_candidate
0,-0.886218,-0.716531,-1.501674,-0.726261,-0.796777,-1.057710,-0.606015,-0.758695,-0.969130,-1.214828,-0.420182,-1.004570,-1.330463,-1.064343,0.472185,0.509455,0.021818,0
1,0.174886,-1.903423,-1.558538,-0.726261,-0.796777,-1.258329,-0.771329,-0.796254,-1.020713,-1.214828,-0.786541,-1.483782,-1.450498,-1.277519,0.472185,0.509455,-1.687118,0
2,0.174886,0.232983,0.100016,-0.726261,-0.796777,-0.079690,-0.220282,0.405639,-0.659630,-0.011881,0.312536,-0.165949,0.109958,-0.277230,0.472185,0.509455,0.293066,0
3,2.562368,-2.061675,-0.828774,-0.726261,-0.796777,-1.158019,-0.881538,-0.458222,-1.020713,-1.415319,-0.237003,-1.603585,0.710134,-1.228325,0.472185,0.509455,-1.371853,0
4,-0.355666,-0.558279,-0.080055,-0.726261,-0.735300,-0.355542,-0.440701,0.405639,-0.659630,-0.813845,-0.237003,-0.764964,0.590099,-0.392018,0.472185,0.509455,1.134430,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,-0.091724,1.113670,1.025399,0.617089,0.763783,0.587060,0.557555,0.723273,0.570653,0.877153,-0.182383,0.660981,0.628128,0.730006,-0.537997,-0.676847,0.302459,0
14088,-0.555920,-0.563355,-1.363893,-0.774400,-0.660391,-1.038473,-0.818088,-0.967234,-0.698884,-0.495522,-0.585917,-0.663611,-1.272335,-1.066681,-0.537997,-0.676847,-0.908281,0
14089,-0.555920,-0.604258,-1.099466,-0.619790,-0.541710,-0.886079,-0.563339,-1.128235,-0.809279,-0.724301,-0.585917,-0.904446,-1.628672,-0.907682,-0.537997,-0.676847,-0.480678,0
14090,-1.484312,-0.358839,-0.806706,-0.155960,-0.185666,-0.759085,-0.919988,-0.685483,-0.698884,-1.181859,-0.384150,-0.904446,-0.559662,-0.685084,-0.537997,-0.676847,0.202020,0
14091,-0.091724,0.541028,0.619314,0.617089,0.467080,0.282272,-0.053842,1.045274,0.073878,0.190816,0.422918,-0.181941,1.103244,0.332509,-0.537997,-0.676847,0.370827,0

In [ ]:
class_1 = df.iloc[np.where(df.Is_MVP_or_MVP_candidate == "1")]
class_1

,Age,G,MP,3P,3PA,2PA,FTA,TRB,AST,STL,BLK,TOV,PF,PTS,W/L%,SRS,TS%,Is_MVP_or_MVP_candidate
5,1.235989,0.826429,1.436338,2.329278,2.523001,1.324645,1.928798,1.044144,1.455287,2.193521,0.312536,1.271686,0.710134,2.182496,0.472185,0.509455,0.629882,1
6,1.235989,0.668176,1.787004,-0.726261,-0.673822,3.907619,2.865577,2.734306,0.784703,2.193521,5.441561,2.349913,1.670415,3.166386,0.472185,0.509455,0.449002,1
18,0.970713,0.509924,1.351041,1.042735,1.170499,2.001735,2.865577,2.846983,1.094203,1.792539,0.495715,1.032080,1.070239,2.379274,1.394055,0.837225,0.568083,1
83,1.235989,1.063807,1.351041,1.203553,0.924589,0.321548,0.771601,-0.157748,5.324037,3.396468,-0.237003,2.349913,0.590099,1.018225,1.469310,1.667292,1.410709,1
84,0.970713,1.063807,1.644842,-0.565443,-0.489390,3.205451,3.416624,2.659187,0.784703,1.792539,1.045254,1.870701,1.430344,2.986006,1.469310,1.667292,0.747133,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13949,0.372472,0.950058,1.469260,0.617089,0.467080,2.466582,2.493645,2.172279,0.901836,0.190816,0.826451,1.022234,0.271791,2.606192,2.476057,2.000638,0.989980,1
13972,0.836668,1.031864,1.270939,-0.774400,-0.779072,2.212592,2.493645,2.856531,0.901836,0.419595,4.054722,1.865156,0.628128,1.874797,1.625939,2.290023,0.730476,1
13973,-0.555920,0.909155,1.119838,-0.465180,-0.541710,2.136395,1.168951,-0.121981,2.060979,1.105932,-0.585917,1.503904,-0.203325,1.652199,1.625939,2.290023,0.669302,1
14015,0.140374,0.663737,1.431485,2.008578,2.365979,2.593576,2.391745,0.723273,2.612951,1.563491,0.221151,2.105991,-0.084546,2.606192,1.061770,1.394824,0.049740,1
14022,0.836668,0.868252,1.771463,-0.465180,-0.423028,2.949162,2.238896,3.742035,1.288217,1.334712,2.642354,1.744739,0.509349,2.256395,-0.823946,-0.822892,0.368273,1